name = "saga-bus-navigator"
pages_build_output_dir = "."
compatibility_date = "2025-11-16"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "GTFS_DATA"
id = "3ae3f515d413458d913a9be942fdf056"

